'use client';
import { useState, useEffect, useRef } from 'react';
import { BookOpen, Layers, Plus, Volume2, X, Search, Check, Shuffle, Gamepad2, Headphones, Trash2, Sparkles, Download, Upload, CheckCircle2 } from 'lucide-react';
import Games from './games';
import WeekPicker from './week-picker';
import { weekKey,weekLabel } from '../lib/weeks';
import { validateBackup,type BackupWord } from '../lib/backup';
import { SAMPLE, parseText, parseRows, cleanCell, keyOf, spokenTerm, posLabel, type Word, type Draft } from '../lib/vocabulary';

type View='library'|'flash'|'quiz'|'match';
const columns=['Từ / Cụm từ','Nghĩa tiếng Việt','Từ đồng nghĩa','Ví dụ'];
const keys: (keyof Draft)[]=['term','meaning','synonyms','example'];
export function shuffled<T>(arr:T[]):T[]{const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
async function api(action:string,data:object){const res=await fetch('/api/words',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...data})});const out:any=await res.json();if(!res.ok)throw new Error(out.error);return out;}
export default function VocabularyApp(){
 const [words,setWords]=useState<Word[]>([]),[loaded,setLoaded]=useState(false),[auth,setAuth]=useState(true),[error,setError]=useState(''),[toast,setToast]=useState(''),[view,setView]=useState<View>('library'),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[importing,setImporting]=useState(false),[help,setHelp]=useState(false),[busy,setBusy]=useState(false),[remove,setRemove]=useState<Word|null>(null);
 const [sampleWords,setSampleWords]=useState(SAMPLE);
 const [selectedWeek,setSelectedWeek]=useState('all'),[restoring,setRestoring]=useState<BackupWord[]|null>(null),[backupError,setBackupError]=useState('');
 const backupInput=useRef<HTMLInputElement>(null);
 const demo=loaded&&words.length===0;
 const allWords=demo?sampleWords:words;
 const visible=selectedWeek==='all'||demo?allWords:allWords.filter(w=>weekKey(w.createdAt)===selectedWeek);
 const sessionKey=selectedWeek+':'+visible.map(w=>w.id).join('|');
 const current=visible.filter(w=>(filter==='all'||(filter==='known'?w.known:!w.known)) && [w.term,w.meaning,w.synonyms].some(s=>s.toLowerCase().includes(query.toLowerCase())));
 const known=visible.filter(w=>w.known).length;
 async function refresh(){try {const r=await fetch('/api/words');if(r.status===401){setAuth(false);setLoaded(true);return;}const d:any=await r.json();if(!r.ok)throw new Error(d.error);setWords(d.words);setAuth(true);setError('');}catch(e){setError(e instanceof Error?e.message:'Không kết nối được. Hãy thử lại.');}finally{setLoaded(true);}}
 useEffect(()=>{void refresh();},[]);
 useEffect(()=>{if(loaded&&selectedWeek!=='all'&&!words.some(w=>weekKey(w.createdAt)===selectedWeek))setSelectedWeek('all');},[loaded,selectedWeek,words]);
 useEffect(()=>{if('serviceWorker'in navigator&&['127.0.0.1','localhost'].includes(location.hostname)){void navigator.serviceWorker.register('/wordnest-sw.js',{scope:'/'}).catch(()=>{});}},[]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(t);},[toast]);
 async function save(drafts:Draft[]){setBusy(true);try {const out=await api('import',{words:drafts});await refresh();setSelectedWeek('all');setImporting(false);setToast('Đã thêm '+out.added+' từ'+(drafts.length>out.added?' · Bỏ qua '+(drafts.length-out.added)+' từ đã có.':'.'));setView('library');}finally{setBusy(false);}}
 function changeWeek(key:string){setSelectedWeek(key);setQuery('');setFilter('all');}
 async function exportBackup(){
  setBusy(true);setBackupError('');
  try{
   const response=await fetch('/api/words',{cache:'no-store'});const fresh:any=await response.json();if(!response.ok)throw new Error(fresh.error||'Chưa tải được dữ liệu mới nhất để sao lưu.');
   const latest:Word[]=fresh.words;
   const payload={format:'wordnest-backup',version:1,exportedAt:new Date().toISOString(),words:latest.map(({term,meaning,synonyms,example,known,createdAt})=>({term,meaning,synonyms,example,known,createdAt}))};
   validateBackup(payload);const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json;charset=utf-8'});if(blob.size>15000000)throw new Error('Bộ từ vượt giới hạn sao lưu 15 MB. Chưa tạo tệp để tránh bản sao lưu không thể khôi phục.');
   setWords(latest);const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='Wordnest-sao-luu-'+new Date().toISOString().slice(0,10)+'.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setToast('Đã tạo tệp sao lưu toàn bộ '+latest.length+' từ, kèm ngày thêm và tiến độ.');
  }catch(e){setBackupError((e as Error).message);}finally{setBusy(false);}
 }
 async function chooseBackup(file?:File){if(!file)return;setBackupError('');try{if(file.size>15000000)throw new Error('Tệp quá lớn. Giới hạn 15 MB.');const parsed=JSON.parse(await file.text());setRestoring(validateBackup(parsed));}catch(e){setBackupError(e instanceof SyntaxError?'Tệp không đúng định dạng JSON.':(e as Error).message);}finally{if(backupInput.current)backupInput.current.value='';}}
 async function restoreBackup(){if(!restoring)return;setBusy(true);setBackupError('');try{const out=await api('restore',{backup:{format:'wordnest-backup',version:1,words:restoring}});await refresh();setSelectedWeek('all');setRestoring(null);setView('library');setToast('Đã khôi phục '+out.added+' từ · Giữ nguyên '+out.skipped+' từ đã có.');}catch(e){setBackupError((e as Error).message);}finally{setBusy(false);}}
 async function rate(w:Word,value:boolean){if(demo){setSampleWords(a=>a.map(x=>x.id===w.id?{...x,known:value?1:0}:x));return;}setBusy(true);try{await api('known',{id:w.id,known:value});setWords(a=>a.map(x=>x.id===w.id?{...x,known:value?1:0}:x));}catch(e){setError((e as Error).message);throw e;}finally{setBusy(false);}}
 function speak(text:string){if(!('speechSynthesis'in window)){setToast('Trình duyệt chưa hỗ trợ giọng đọc. Bạn có thể dùng eJOY.');return;}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.88;const voice=window.speechSynthesis.getVoices().find(v=>v.lang==='en-US')||window.speechSynthesis.getVoices().find(v=>v.lang.startsWith('en'));if(voice)u.voice=voice;u.onerror=()=>setToast('Không phát được âm thanh. Hãy thử lại hoặc dùng eJOY.');window.speechSynthesis.speak(u);}
 const wordsRef=useRef(visible); wordsRef.current=visible;
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const controller=new AbortController();const definitions=[{name:'list_vocabulary',title:'Xem bộ từ',description:'Read the vocabulary currently displayed, including whether words are marked known.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object');return {words:wordsRef.current};}},{name:'start_vocabulary_practice',title:'Mở chế độ học',description:'Navigate to flashcards, a meaning quiz or a matching game. This does not change saved vocabulary or progress.',inputSchema:{type:'object',properties:{mode:{type:'string',enum:['flash','quiz','match']}},required:['mode'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:any)=>{if(!input||Object.keys(input).some(k=>k!=='mode')||!['flash','quiz','match'].includes(input.mode))throw new Error('Mode must be flash, quiz or match');setView(input.mode);await new Promise<void>(r=>requestAnimationFrame(()=>r()));return {opened:input.mode};}}];for(const tool of definitions){try{void Promise.resolve(context.registerTool(tool,{signal:controller.signal})).catch(()=>{});}catch{}}return()=>controller.abort();},[]);
 const switchView=(v:View)=>{setView(v);setQuery('');setFilter('all');};
 return <div className="shell">
  <aside className="sidebar"><a className="brand" href="/" aria-label="Wordnest trang chủ"><span className="brand-icon"><BookOpen size={23}/></span>wordnest<span className="brand-dot">.</span></a><div className="side-label">GÓC HỌC CỦA BẠN</div>
   <nav aria-label="Chế độ học">{([{id:'library',label:'Bộ từ vựng',icon:BookOpen},{id:'flash',label:'Thẻ ghi nhớ',icon:Layers},{id:'quiz',label:'Chọn nghĩa',icon:Sparkles},{id:'match',label:'Ghép cặp',icon:Gamepad2}] as const).map(n=><button key={n.id} className={'nav-item '+(view===n.id?'active':'')} onClick={()=>switchView(n.id)}><n.icon size={20}/>{n.label}{n.id==='library'&&<span className="nav-count">{allWords.length}</span>}</button>)}</nav>
   <div className="side-bottom"><div className="ejoy-mark"><Headphones size={23}/><strong>Học cùng eJOY</strong></div><p>Bôi đen từ tiếng Anh để tra và nghe bằng tiện ích của bạn.</p><button className="text-button" onClick={()=>setHelp(true)}>Cách sử dụng eJOY</button></div><div className="side-foot"><span className="mini-avatar">W</span><div>Không gian của bạn<small>English · Tiếng Việt</small></div></div>
  </aside>
  <main className="main"><header className="topbar"><span>HỌC MỖI NGÀY, NHỚ LÂU HƠN</span><span className="save-status">{demo?'Đang xem bộ mẫu':loaded&&!error?'Bộ từ đã lưu':'Đang kết nối…'}</span></header>
   <div className="page-heading"><div><p className="eyebrow">MY WORDS / {view==='library'?'01':view==='flash'?'02':view==='quiz'?'03':'04'}</p><h1>{view==='library'?'Từng từ, một bước tiến.':view==='flash'?'Chậm một chút. Nhớ lâu hơn.':view==='quiz'?'Bạn nhớ nghĩa nào?':'Tìm đúng cặp của nhau.'}</h1><p>{view==='library'?'Gom những từ bạn gặp. Biến chúng thành những từ bạn nhớ.':view==='flash'?'Đọc từ, thử nhớ nghĩa, rồi tự kiểm tra.':view==='quiz'?'Chọn nghĩa tiếng Việt đúng với từ tiếng Anh.':'Chọn một từ tiếng Anh và nghĩa tương ứng.'}</p></div><button className="primary" onClick={()=>setImporting(true)}><Plus size={19}/>Thêm từ vựng</button></div>
   {!auth&&<div className="notice"><span>Bạn đang học thử. Đăng nhập để lưu từ và tiến độ.</span><a className="text-button" href="/signin-with-chatgpt?return_to=%2F" target="_top">Đăng nhập với ChatGPT</a></div>}
   {error&&<div className="error" role="alert">{error}<button onClick={()=>void refresh()}>Thử tải lại</button></div>}
   {demo&&<div className="demo-banner"><span><strong>5 từ mẫu của bạn</strong> · Học thử ngay hoặc dán bảng từ mới.</span><button disabled={busy} onClick={()=>void save(SAMPLE).catch(e=>setError(e.message))}>Lưu 5 từ mẫu</button></div>}
   {loaded&&!demo&&<WeekPicker words={words} selected={selectedWeek} onChange={changeWeek}/>}
   {selectedWeek!=='all'&&!demo&&<div className="week-context"><span><strong>Đang học: {weekLabel(selectedWeek)}</strong> · {visible.length} từ. Thẻ ghi nhớ và trò chơi chỉ dùng bộ từ này.</span><button className="text-button" onClick={()=>changeWeek('all')}>Bỏ lọc tuần</button></div>}
   <section className="stats" aria-label="Tiến độ học"><div><span>Tổng số từ</span><strong>{visible.length.toString().padStart(2,'0')}</strong><BookOpen/></div><div><span>Đã nhớ</span><strong>{known.toString().padStart(2,'0')}</strong><CheckCircle2/></div><div><span>Cần ôn thêm</span><strong>{(visible.length-known).toString().padStart(2,'0')}</strong><Layers/></div><div className="progress-stat"><span>Tiến độ của bạn{demo?' · học thử':''}</span><strong>{visible.length?Math.round(known/visible.length*100):0}<small>%</small></strong><div className="progress"><i style={{width:(visible.length?known/visible.length*100:0)+'%'}}/></div></div></section>
   {!loaded?<div className="empty">Đang tải bộ từ của bạn…</div>:view==='library'?<>
    <div className="section-head"><div><h2>Bộ từ vựng <span>{visible.length}</span></h2><p>Tiếng Anh ở đây luôn có thể bôi đen để dùng eJOY.</p></div><button className="secondary" onClick={()=>switchView('flash')}><Layers size={17}/>Ôn bằng thẻ</button></div>
    <div className="toolbar"><div className="pills">{[['all','Tất cả'],['new','Cần ôn'],['known','Đã nhớ']].map(([id,label])=><button key={id} onClick={()=>setFilter(id)} className={filter===id?'selected':''}>{label}</button>)}</div><label className="search"><Search size={17}/><input placeholder="Tìm từ hoặc nghĩa…" aria-label="Tìm từ hoặc nghĩa" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
    <div className="word-table"><div className="table-header"><span>TỪ / CỤM TỪ</span><span>NGHĨA & TỪ ĐỒNG NGHĨA</span><span>VÍ DỤ</span><span></span></div>{current.map((w,i)=><article className="word-row" key={w.id}><div className="word-cell"><span className="row-number">{String(i+1).padStart(2,'0')}</span><div><span lang="en" className="term">{spokenTerm(w.term)}</span><small className="pos">{posLabel(w.term)||'từ / cụm từ'}</small><button className="sound" aria-label={'Nghe '+spokenTerm(w.term)} onClick={()=>speak(spokenTerm(w.term))}><Volume2 size={17}/></button></div></div><div className="meaning-cell"><p>{w.meaning}</p><p lang="en" className="synonyms"><span>≈</span> {w.synonyms||'Chưa có từ đồng nghĩa'}</p></div><div className="example" lang="en">{w.example||'Chưa có ví dụ.'}</div><div className="row-actions"><button disabled={busy} className={'known-button '+(w.known?'is-known':'')} aria-label={w.known?'Đánh dấu cần ôn '+w.term:'Đánh dấu đã nhớ '+w.term} title={w.known?'Đã nhớ · nhấn để ôn lại':'Đánh dấu đã nhớ'} onClick={()=>void rate(w,!w.known).catch(()=>{})}><Check size={18}/></button>{!demo&&<button aria-label={'Xóa '+w.term} className="delete" onClick={()=>setRemove(w)}><Trash2 size={15}/></button>}</div></article>)}{!current.length&&<div className="empty">Không có từ phù hợp. Hãy thử từ khóa hoặc bộ lọc khác.</div>}</div>
    <footer className="table-footer"><span>{current.length} từ trong bộ từ của bạn{demo?' · bản học thử':''}</span><span>Một chút mỗi ngày là đủ.</span></footer>
   </>:view==='flash'?<Flash key={sessionKey} words={visible} onRate={rate} speak={speak} busy={busy}/>:<Games key={sessionKey} words={visible} mode={view} speak={speak}/>}
   {loaded&&<section className="backup-bar" aria-label="Sao lưu bộ từ"><div><strong>Giữ lại hành trình học</strong><p>Sao lưu toàn bộ từ, tuần đã thêm và tiến độ vào một tệp.</p></div><div className="backup-actions"><button className="secondary" disabled={!words.length||busy} onClick={exportBackup}><Download size={17}/>Sao lưu toàn bộ</button><button className="secondary" disabled={busy} onClick={()=>backupInput.current?.click()}><Upload size={17}/>Khôi phục</button><input ref={backupInput} type="file" accept=".json,application/json" hidden aria-label="Chọn tệp sao lưu Wordnest" onChange={e=>void chooseBackup(e.target.files?.[0])}/></div>{backupError&&!restoring&&<p className="error" role="alert">{backupError}</p>}</section>}
  </main>
  {importing&&<ImportDialog onClose={()=>setImporting(false)} onSave={save} busy={busy} existing={words}/>}
  {restoring&&<Modal title="Khôi phục bộ từ" onClose={busy?()=>{}:()=>{setRestoring(null);setBackupError('');}}><p>Tệp chứa <strong>{restoring.length} từ</strong>, kèm ngày thêm và trạng thái đã nhớ.</p><p className="restore-note">Chỉ thêm những từ chưa có. Từ trùng cả cách viết và nghĩa được bỏ qua; ngày thêm và tiến độ hiện tại của bạn được giữ nguyên.</p>{backupError&&<p className="error" role="alert">{backupError}</p>}<div className="dialog-actions"><button className="secondary" disabled={busy} onClick={()=>setRestoring(null)}>Hủy</button><button className="primary" disabled={busy} onClick={()=>void restoreBackup()}>{busy?'Đang khôi phục…':'Khôi phục từ tệp'}</button></div></Modal>}
  {help&&<Modal title="Dùng eJOY trên Wordnest" onClose={()=>setHelp(false)}><ol className="help-list"><li>Mở trang này bằng Chrome, Edge, Cốc Cốc hoặc Brave đã cài eJOY.</li><li>Bôi đen hoặc nhấp đúp từ tiếng Anh, rồi chọn biểu tượng eJOY để tra và nghe.</li><li>Nếu chưa thấy biểu tượng, kiểm tra eJOY đã bật và được phép hoạt động trên trang này trong phần quản lý tiện ích.</li></ol><p>Tiện ích có thể không hoạt động trong khung xem trước. Hãy mở đường dẫn trang bằng trình duyệt của bạn. Nút loa trên Wordnest dùng giọng đọc của trình duyệt, độc lập với eJOY.</p><a className="text-button" href="https://ejoy-english.com/en/help/look-up-new-words-while-reading-online-text?clearCache=true" target="_blank" rel="noreferrer">Xem hướng dẫn chính thức của eJOY</a></Modal>}
  {remove&&<Modal title="Xóa từ này?" onClose={()=>setRemove(null)}><p><strong lang="en">{remove.term}</strong> sẽ được xóa khỏi bộ từ và tiến độ học của bạn.</p><div className="dialog-actions"><button className="secondary" onClick={()=>setRemove(null)}>Giữ lại</button><button className="danger" disabled={busy} onClick={async()=>{setBusy(true);try{await api('delete',{id:remove.id});setWords(a=>a.filter(w=>w.id!==remove.id));setRemove(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Xóa từ</button></div></Modal>}
  {toast&&<div className="toast" role="status"><CheckCircle2 size={19}/>{toast}</div>}
 </div>;
}
export function Modal({title,onClose,children,wide=false}:{title:string;onClose:()=>void;children:React.ReactNode;wide?:boolean}){
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close();},[]);
 return <dialog ref={ref} className={wide?'modal wide':'modal'} onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><header><h2>{title}</h2><button className="icon-button" aria-label="Đóng" onClick={onClose}><X/></button></header>{children}</dialog>;
}
function ImportDialog({onClose,onSave,busy,existing}:{onClose:()=>void;onSave:(w:Draft[])=>Promise<void>;busy:boolean;existing:Word[]}){
 const [text,setText]=useState(''),[drafts,setDrafts]=useState<Draft[]>([]),[issues,setIssues]=useState<string[]>([]),[err,setErr]=useState(''),[parsed,setParsed]=useState(false);
 const duplicates=drafts.filter((w,i)=>existing.some(x=>keyOf(x)===keyOf(w))||drafts.slice(0,i).some(x=>keyOf(x)===keyOf(w))).length;
 function analyse(t:string){const r=parseText(t);setDrafts(r.words);setIssues(r.issues);setParsed(true);setErr('');}
 function paste(e:React.ClipboardEvent<HTMLTextAreaElement>){const html=e.clipboardData.getData('text/html');if(!html)return;const doc=new DOMParser().parseFromString(html,'text/html');const tables=doc.querySelectorAll('table');if(!tables.length)return;
  doc.querySelectorAll('script,style').forEach(n=>n.remove());doc.querySelectorAll('br').forEach(n=>n.replaceWith(' '));doc.querySelectorAll('p,div,li').forEach(n=>n.appendChild(doc.createTextNode(' ')));
  const rows=Array.from(tables).flatMap(t=>Array.from(t.rows).map(r=>Array.from(r.cells).map(c=>cleanCell(c.textContent||''))));
  const r=parseRows(rows);if(r.words.length){e.preventDefault();setText(rows.map(r=>r.join('\t')).join('\n'));setDrafts(r.words);setIssues(r.issues);setParsed(true);setErr('');}
 }
 return <Modal title="Thêm từ từ ChatGPT" onClose={busy?()=>{}:onClose} wide><p className="muted">Dán cả bảng 4 cột. Wordnest tự tách từ, nghĩa, từ đồng nghĩa và ví dụ.</p><label className="input-label" htmlFor="paste-table">Bảng từ vựng của bạn</label><textarea autoFocus id="paste-table" className="paste-area" value={text} onPaste={paste} onChange={e=>{setText(e.target.value);setParsed(false);setDrafts([]);setIssues([]);}} placeholder={'| Từ / Cụm từ | Nghĩa | Từ đồng nghĩa | Ví dụ |\n| abandon (v.) | từ bỏ | leave, give up | They decided to abandon the project. |'}/>
  <div className="parse-actions"><button className="secondary" onClick={()=>analyse(text)} disabled={!text.trim()}><Upload size={16}/>Tách cột & xem trước</button><button className="text-button" onClick={()=>{const t='| Từ / Cụm từ | Nghĩa | Từ đồng nghĩa | Ví dụ |\n'+SAMPLE.map(w=>'| '+keys.map(k=>w[k]).join(' | ')+' |').join('\n');setText(t);analyse(t);}}>Dùng 5 từ mẫu</button></div>
  {issues.length>0&&<div className="warning"><strong>{issues.length} dòng cần kiểm tra</strong><ul>{issues.slice(0,8).map((x,i)=><li key={i}>{x}</li>)}</ul><p>Các dòng này chưa được nhập. Hãy sửa bảng rồi tách cột lại, hoặc chỉ lưu các dòng hợp lệ bên dưới.</p></div>}
  {parsed&&drafts.length>0&&<><div className="preview-heading"><h3>Xem trước · {drafts.length} từ</h3><span>Có thể sửa từng ô</span></div><div className="import-preview"><table><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{drafts.map((w,i)=><tr key={i}>{keys.map((k,j)=><td key={k}><textarea aria-label={columns[j]+' dòng '+(i+1)} value={w[k]} onChange={e=>setDrafts(a=>a.map((v,n)=>n===i?{...v,[k]:e.target.value}:v))}/></td>)}</tr>)}</tbody></table></div><p className="muted">{duplicates?duplicates+' từ trùng từ và nghĩa sẽ được bỏ qua.':'Các từ cùng cách viết nhưng khác nghĩa vẫn được giữ riêng.'}</p></>}
  {parsed&&!drafts.length&&<p className="error">Chưa có dòng hợp lệ để thêm.</p>}{err&&<p className="error" role="alert">{err}</p>}
  <div className="dialog-actions"><span className="muted">Tối đa 500 từ mỗi lần</span><button className="secondary" disabled={busy} onClick={onClose}>Hủy</button><button className="primary" disabled={busy||!drafts.length||drafts.length>500||drafts.some(w=>!w.term.trim()||!w.meaning.trim())} onClick={()=>void onSave(drafts).catch(e=>setErr(e.message))}>{busy?'Đang lưu…':'Lưu '+(drafts.length-duplicates)+' từ mới'}</button></div>
 </Modal>;
}
function Flash({words,onRate,speak,busy}:{words:Word[];onRate:(w:Word,b:boolean)=>Promise<void>;speak:(s:string)=>void;busy:boolean}){
 const [list,setList]=useState(words),[index,setIndex]=useState(0),[flipped,setFlipped]=useState(false),[finished,setFinished]=useState(false),[rated,setRated]=useState(0);
 const word=list[index];
 function next(){setFlipped(false);if(index+1>=list.length)setFinished(true);else setIndex(index+1);}
 function restart(onlyNew=false){const a=words.filter(w=>!onlyNew||!w.known);setList(shuffled(a));setIndex(0);setFlipped(false);setFinished(false);setRated(0);}
 if(finished)return <div className="session-done"><CheckCircle2 size={52}/><h2>Thêm một lượt học hoàn thành!</h2><p>Bạn vừa xem {list.length} từ và đánh dấu nhớ {rated} từ trong lượt này.</p><button className="primary" onClick={()=>restart()}>Học lại bộ từ</button></div>;
 return <div className="study"><div className="study-top"><span>THẺ {list.length?index+1:0} / {list.length}</span><div><button disabled={busy} className="text-button" onClick={()=>restart(true)}>Chỉ từ cần ôn</button><button disabled={busy} className="secondary" onClick={()=>restart()}><Shuffle size={16}/>Trộn thẻ</button></div></div>{word?<><div className="flash-card"><span className="card-kicker">{flipped?'ĐÁP ÁN':'BẠN CÒN NHỚ TỪ NÀY?'}</span><div className="flash-word" lang="en">{spokenTerm(word.term)}</div><span className="flash-pos">{posLabel(word.term)}</span><button className="sound large" aria-label="Nghe từ" onClick={()=>speak(spokenTerm(word.term))}><Volume2 size={22}/></button>{flipped?<div className="card-answer"><h3>{word.meaning}</h3><p lang="en" className="synonyms">≈ {word.synonyms||'Chưa có từ đồng nghĩa'}</p><p lang="en">{word.example}</p></div>:<p className="card-prompt">Thử nói nghĩa của từ trước khi xem đáp án.</p>}</div><div className="flash-controls">{!flipped?<button className="primary" onClick={()=>setFlipped(true)}>Hiện nghĩa</button>:<><button className="secondary" disabled={busy} onClick={()=>void onRate(word,false).then(next).catch(()=>{})}>Cần ôn thêm</button><button className="primary" disabled={busy} onClick={()=>void onRate(word,true).then(()=>{setRated(r=>r+1);next();}).catch(()=>{})}><Check size={18}/>Mình đã nhớ</button></>}</div><button className="text-button skip" onClick={next} disabled={busy}>Bỏ qua từ này</button><p className="study-hint">Bôi đen từ để dùng eJOY · Nút loa dùng giọng đọc trình duyệt</p></>:<div className="empty">Bạn đã đánh dấu nhớ tất cả các từ.<button className="primary" onClick={()=>restart()}>Ôn lại toàn bộ</button></div>}</div>;
}
